name: Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    name: Release
    uses: ctfpilot/ci/.github/workflows/release.yml@v1.3.0
    permissions:
      contents: write
      packages: write
      id-token: write
    secrets:
      RELEASE_GH_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}
    with:
      repository: ctfpilot/<repository-name>
      ENVIRONMENT: Release

  update-develop:
    if: github.ref == 'refs/heads/main'
    name: "Update Develop Branch"
    needs:
      - release
    uses: ctfpilot/ci/.github/workflows/develop-update.yml@v1.3.0
    permissions:
      contents: read
      pull-requests: write
      issues: write
    with:
      repository: ctfpilot/<repository-name>
